# Generated by Django 3.2.2 on 2021-05-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='companyaccount',
            name='acc_name',
            field=models.CharField(max_length=128),
        ),
    ]
