# Generated by Django 3.2.2 on 2021-06-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210531_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
    ]
